[features]
seeds = false
[programs.localnet]
counter_program = "AkZZu7ipdyxhxt8NcZQt2WBRH6KtXqx5AWzb2c1LsTgs"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/ricardocastelloroman/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
